---
title: Media Favorites
date-modified: '2025-07-14'
---

This page is a list of things I have read, watched, or otherwise engaged with. It's not necessarily a list of favorites, preferences, or recommendations, but rather like a personal reading log with the following purposes:

1) To note for my own personal record, revisitation, and quick reference
2) To share with others who find themselves exploring similar domains

That I have shared an author or topic here is not an endorsement.

## Podcasts

Here's a list of my favorite podcasts to listen to. These are wholehearted recommendations.

| | |
|-|-|
|[Nullius in Verba](https://nulliusinverba.podbean.com/) with [Daniel Lakens](https://sites.google.com/site/lakens2/Home) and [Smriti Mehta](https://www.linkedin.com/in/smriti-mehta-6a5aab51)<br> "A podcast about science, what it is, and what it could be"| <iframe style="border-radius:12px" src="https://open.spotify.com/embed/show/0tw0yVZxuf2X4iN6kFay5A?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>|
|[Brain Inspired](https://braininspired.co/podcast/) with [Paul Middlebrooks](https://www.thetransmitter.org/contributor/paul-middlebrooks/)|<iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/3AMzjyLLbz4u9oBupyCBMw?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>|
|[Stanford Psychology Podcast](https://www.stanfordpsychologypodcast.com/episodes) with [Eric Neumann, Anjie Cao and others](https://www.stanfordpsychologypodcast.com/meet-the-team)|<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/episode/3XETUFtldevrrpNTyo1cxq?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>|
|[Brain Science](https://brainsciencepodcast.com/) with [Ginger Campbell](https://www.virginiacampbellmd.com)|<iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/2nMGVNzw4K2LMrBNe72bBi?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>|

## YouTube

Computational Neuroscience with Artem Kirsanov

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/Dykkubb-Qus?si=ArjN0bx-jKdlolsE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

Computerphile with Sean Riley and Brady Haran

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/844U9T_SOrA?si=15UtRS2zDfa0lwQf" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

3Blue1Brown with Grant Sanderson

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/eMlx5fFNoYc?si=HDfKlkxOVPepAmB8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

QuantPsych with Dustin Fife

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/c_tYZxQLoDA?si=J1ngN3lX53PzFKuz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>